# DATASOURCE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:fiap-fastfood;INIT=CREATE SCHEMA IF NOT EXISTS FIAP_FOOD
spring.datasource.username=sa
spring.datasource.password=
# H2 CLIENT
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=FIAP_FOOD

jwt.secret=IMvCkrq577YvcmXLyRJuitNefug5L5OXRz3SiSHQbp0=
jwt.expiration=3600000
